name = "chesapeake_shell"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "doverdesign"
database_id = "5a6da159-9736-4038-b8b7-a5c4e6e64256"
preview_database_id = "5a6da159-9736-4038-b8b7-a5c4e6e64256"
migrations_dir = "db/migrations"
